[versions]
android-gradle-plugin = "8.1.1"
kotlin = "1.9.0"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
